services:
  - type: web
    name: ai-webbuilder
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: FLASK_ENV
        value: production
      - key: PYTHON_VERSION
        value: 3.8.0
      - key: CHROMEDRIVER_PATH
        value: /usr/local/bin/chromedriver
      - key: GOOGLE_CHROME_BIN
        value: /usr/bin/google-chrome-stable
    buildCommand: |
      # Install Chrome
      wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add -
      echo "deb http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google.list
      apt-get update && apt-get install -y google-chrome-stable
      
      # Install ChromeDriver
      CHROME_VERSION=$(google-chrome --version | cut -d ' ' -f3 | cut -d '.' -f1)
      CHROMEDRIVER_VERSION=$(curl -s "https://chromedriver.storage.googleapis.com/LATEST_RELEASE_$CHROME_VERSION")
      curl -Lo /tmp/chromedriver.zip "https://chromedriver.storage.googleapis.com/$CHROMEDRIVER_VERSION/chromedriver_linux64.zip"
      unzip -q /tmp/chromedriver.zip -d /usr/local/bin/
      chmod +x /usr/local/bin/chromedriver
      
      pip install -r requirements.txt 